name: Prep Your Home
favicon: null
layout_spectrum: 0.9062300682999194
typography_spectrum: 0.5360360811464489
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.055795758264139295
  lightness: 0.5294787685852498
  saturation: 0.9244110721629113
  rhythmicContrast: 0.8542500222101808
purpose: []
