name: Prep Your Home
favicon: null
layout_spectrum: 0.8808
typography_spectrum: 0.78642
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#ed2225'
    - '#727272'
    - '#a6a6a6'
  brandStrength: 0.125
  lightness: 0.5294787685852498
  saturation: 0.9244110721629113
  rhythmicContrast: 0.75
purpose: []
